RestaurantBundle\Entity\ImageMenu:
    type: entity
    
    manyToOne:
        menu:
            targetEntity: Menu
            inversedBy: images
            cascade: ["persist", "merge"]
            joinColumn:
                name: menu_id
                referencedColumnName: id
                
    table: null
    repositoryClass: RestaurantBundle\Repository\ImageMenuRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        alt:
            type: string
            length: 255
        filename:
            type: string
            length: 255
            unique: false
            nullable: true
        created:
            type: datetime
        updated:
            type: datetime
    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]
