RestaurantBundle\Entity\Subscriber:
    type: entity
    table: null
    repositoryClass: RestaurantBundle\Repository\SubscriberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
            unique: true
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
