<?php

namespace RestaurantBundle\Repository;

/**
 * FacebookEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookEventRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * vérifie si les id facebook des events 
     * données en paramètres existent dans la base de données
     * 
     * @return array un tableau des id des facebookEvents présent en bdd
     */
    public function eventsExists(array $facebookEvents)
    {
        
        $existingEvents = $this->findBy([
            'facebookId' => [
               $facebookEvents[0]['id'],
               $facebookEvents[1]['id']                
            ]
        ]);
        
        /* récupère uniquement les id */
        $eventsId = [];
        foreach($existingEvents as $event)
        {
            $eventsId[] = $event->getFacebookId();
        }
        
        return $eventsId;
    }
    
    /**
     * Retourne les events ayant une date supérieures à aujourd'hui
     */
    public function findLast()
    {
        $today = new \DateTime();
        
        return $this->createQueryBuilder('f')->where('f.dateStart > :today')
                ->setParameter('today', $today)
                ->orderBy('f.dateStart', 'ASC')
                ->getQuery()->getResult();
    }

}
