<?php

namespace RestaurantBundle\Repository;

/**
 * ImageMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
