<?php

namespace RestaurantBundle\Repository;



/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProductsAvailable()
    {
        $qb = $this->createQueryBuilder('p')
                ->join('p.productCategories', 'c')
                ->addSelect('c')
                ->where('p.available = 1')
                
                ->orderBy('p.name', 'asc')
        ;

        return $qb->getQuery()
                ->getResult();
    }
    
    /*
     * @return Product
     */
    public function getOneProductById($id)
    {
        $qb = $this->createQueryBuilder('p')
                ->join('p.productCategories', 'c')
                ->addSelect('c')
                ->where('p.id = :id')
                ->setParameter(':id', $id)
                ;
                
        return $qb->getQuery()
                ->getSingleResult()
                ;     
    }
}
