<?php

namespace RestaurantBundle\Repository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Doctrine\ORM\EntityRepository {

    /*
     * Récupère uniquement les catégories des produits available
     */
    public function getAllCategoriesAvailable() {
        $qb = $this->createQueryBuilder('c')
                ->join('c.products', 'p')
                ->addSelect('p')
                ->where('p.available = 1')
                ->orderBy('c.name', 'asc')
        ;

        return $qb->getQuery()
                        ->getResult();
    }

}
